// Generated By Unreal Engine

#include "OpenCV.h"

#define LOCTEXT_NAMESPACE "FOpenCVModule"

void FOpenCVModule::StartupModule() { }

void FOpenCVModule::ShutdownModule() { }

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FOpenCVModule, OpenCV)