// Generated by Unreal Engine

#pragma once

#include "GameFramework/GameMode.h"
#include "OpenCVProjectGameMode.generated.h"

/**
 * 
 */
UCLASS()
class OPENCVPROJECT_API AOpenCVProjectGameMode : public AGameMode
{
	GENERATED_BODY()
	
	
	
	
};
